title: "Sandeep — PhD Scholar, IIT (ISM) Dhanbad"
name: "Sandeep"
email: "sandeep.s.fin03@gmail.com"
description: "Personal research blog and academic profile — IIT (ISM) Dhanbad."
url: "https://sandyfin03.github.io"   # GitHub Pages URL
baseurl: "" 
repository: "sandyfin03/sandyfin03.github.io"

# Theme settings
remote_theme: mmistakes/minimal-mistakes@4.24.0   # versioned remote theme
minimal_mistakes_skin: "default"
locale: "en-IN"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

paginate: 5
paginate_path: "/blog/page:num/"

# Author profile
author:
  name: "Sandeep Singh"
  avatar: "/assets/img/Sandeep_Photo.jpg"   # uploaded photo path
  bio: "PhD Research Scholar at IIT (ISM) Dhanbad. Research: FinTech, Crypto, Forecasting (LSTM/ARIMA)."
  location: "Dhanbad, India"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:sandeep.s.fin03@gmail.com"
    - label: "Phone"
      icon: "fas fa-fw fa-phone"
      url: "tel:+917007720434"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sandyfin03"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/sandeep-singh-85664b265"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0009-0005-6386-3342"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar ai-fw"
      url: "https://scholar.google.com/citations?user=YOURID"   # replace with actual ID
    - label: "Curriculum Vitae"
      icon: "fas fa-fw fa-file-pdf"
      url: "/assets/files/CV-Sandeep.pdf"

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sandyfin03"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/sandeep-singh-85664b265"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0009-0005-6386-3342"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar ai-fw"
      url: "https://scholar.google.com/citations?user=YOURID"
    - label: "Curriculum Vitae"
      icon: "fas fa-fw fa-file-pdf"
      url: "/assets/files/CV-Sandeep.pdf"

# Collections (optional pages)
collections:
  pages:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      read_time: true
      author_profile: true
      share: true
      comments: false

# SEO
seo:
  type: "Person"

# Sitemap
timezone: "Asia/Kolkata"
