title: "Sandeep — PhD Scholar, IIT (ISM) Dhanbad"
description: "Investor Sentiment · Crypto Adoption · Portfolio Optimization"

url: "https://sandyfin03.github.io"
baseurl: "/sandeep3799-blog"   # important for project pages

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

author:
  name: "Sandeep"
  avatar: "/assets/img/Sandeep_Photo.jpg"
  bio: "PhD Scholar at IIT (ISM) Dhanbad"

navigation:
  - title: "Research"
    url: /research/
  - title: "Blog"
    url: /blog/
  - title: "Teaching"
    url: /teaching/
  - title: "CV"
    url: /assets/cv/CV-Sandeep.pdf
