title: "Sandeep — PhD Scholar, IIT (ISM) Dhanbad"
name: "Sandeep"
email: "your.email@iitism.ac.in"
description: "Personal research blog and academic profile — IIT (ISM) Dhanbad."
url: "" # e.g. https://<username>.github.io
baseurl: "" # e.g. /repo-name
repository: ""

# Minimal Mistakes settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default" # options: default, air, aqua, contrast, dark, dirt, neon, mint, plume, sunrise
locale: "en-IN"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

paginate: 5
paginate_path: "/blog/page:num/"

# Author profile
author:
  name: "Sandeep"
  avatar: "/assets/img/profile.jpg"
  bio: "PhD Research Scholar in [IIT (ISM) Dhanbad](https://www.iitism.ac.in). Interests: FinTech, Crypto, Forecasting (LSTM/ARIMA)."
  location: "Dhanbad, India"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:your.email@iitism.ac.in"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/your-username"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar ai-fw"
      url: "https://scholar.google.com/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/your-handle/"

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/your-username"
    - label: "Twitter"
      icon: "fab fa-fw fa-x-twitter"
      url: "https://x.com/your-handle"

# Collections (optional pages)
collections:
  pages:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      read_time: true
      author_profile: true
      share: true
      comments: false

# SEO
seo:
  type: "Person"

# Analytics (optional)
# google_analytics: G-XXXXXXXXXX

# Sitemap
timezone: "Asia/Kolkata"
